name: xscore
description: xscore
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: any
  dio: ^3.0.10
  dio_http_cache: ^0.2.11
  flutter_screenutil:  ^4.0.3+3
#  flutter_color_plugin:
  encrypt: any
  url_launcher:   #一款支持android和IOS的插件，其中包含打开网址、发送邮件、拨打电话、以及发送信息功能。
  oktoast: any
  connectivity:
  decimal: ^0.3.5
  permission_handler: ^8.1.0 #权限申请
  jpush_flutter: ^2.1.2  #极光推送
  notification_permissions:  #检测通知权限
  event_bus: ^1.1.1
  ndialog: ^3.3.2
  cached_network_image: ^2.0.0
  provider: 4.0.3
  fluro: ^1.7.7   #路由管理
  scan: ^0.0.3 #扫描二维码
  flutter_webview_plugin: ^0.3.11
  share: ^0.6.3+6       #调用系统分享功能
  package_info: ^0.4.3 # package_info_plus: ^1.3.0
  open_file: ^2.0.3
  ota_update: ^2.4.1
  path_provider: ^1.1.0 #文件路径
  sqflite: ^1.1.6+3
  convert: ^2.1.1
  crypto: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
